### ISSUE TITLE
Pycalphad 0.8.2 on Windows

### ISSUE THREAD

**Issue by jan-janssen** [calphad2020/constructor#1]
@richardotis for windows I only find pycalphad 0.8 but no 0.8.2 - Can you take a look at this?

**Comment by jan-janssen** [comment]
This also restricts espei to version 0.7.2

**Comment by richardotis** [comment]
We probably would like to support Python 3.8 on Windows as well. I have only been able to build packages for 3.6 and 3.7 so far. For 3.8, we are missing a key dependency which will probably not be resolved until I get the packages on conda-forge updated.

**Comment by jan-janssen** [comment]
We have a similar issue with the Lammps package, so I guess for now Python 3.7 is the best choice.
